# Generated by Django 3.2.12 on 2024-01-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productscategoty',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
